name: "Image: Lint/scan"

on:
  workflow_call:
    inputs:
      continue_on_lint_error:
        description: Whether to continue after a Trivy lint error.
        required: false
        default: true
        type: boolean
      continue_on_scan_error:
        description: Whether to continue after a Dockle scan error.
        required: false
        default: true
        type: boolean
      file:
        description: The path to the Dockerfile.
        required: true
        type: string

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.file }}
          outputs: type=docker,dest=/tmp/image.tar
          target: release-stage
          push: false
          tags: app-image:${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: /tmp/image.tar
          retention-days: 1

  lint:
    name: Dockle Lint
    runs-on: ubuntu-20.04
    needs:
      - build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: .

      - name: Load Docker image
        run: |
          docker load --input ./image.tar

      - name: Lint with Dockle
        uses: erzz/dockle-action@v1
        with:
          image: app-image:${{ github.sha }}
          exit-code: 1
          failure-threshold: FATAL
          timeout: "10m"
          continue-on-error: ${{ inputs.continue_on_lint_error }}

  scan:
    name: Trivy Scan
    runs-on: ubuntu-20.04
    needs:
      - build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: .

      - name: Load Docker image
        run: |
          docker load --input ./image.tar
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-image:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: "10m"
        continue-on-error: ${{ inputs.continue_on_scan_error }}
