# Note: Used by this GitHub repository.

name: "Check GitHub YAML files"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  PYTHON_PACKAGES: |
    jsonschema==4.9.1
    ruamel.yaml==0.17.21
    requests==2.27.1
  PYTHON_VERSION: 3.9
  GITHUB_ACTIONS_BRANCHORTAG: main
  GITHUB_ACTIONS_RAWCONTENT_URL: https://raw.githubusercontent.com/cascadin/github-actions

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: ${{ env.PYTHON_PACKAGES }}

      - name: Download workflow dependencies
        run: |-
          # Python files
          for FILENAME in github-schema-validate.py
          do
            curl -fsSL ${{ env.GITHUB_ACTIONS_RAWCONTENT_URL }}/${{ env.GITHUB_ACTIONS_BRANCHORTAG }}/scripts/$FILENAME -o $FILENAME
          done
           
      - name: Validate Schemas
        working-directory: .
        env:
          GITHUB_YAML_PATH: './checkout/.github'
        run: |-
          python github-schema-validate.py
